name: Déployer le site sur Alwaysdata

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > id_ed25519
          chmod 600 id_ed25519
          eval $(ssh-agent -s)
          ssh-add id_ed25519

      - name: Deploy to Alwaysdata
        run: ssh -o StrictHostKeyChecking=no abysse@ssh-abysse.alwaysdata.net 'cd ~/www/TP-web && git pull origin main'
