name: Connexion SSH à Alwaysdata

on:
  push:
    branches:
      - main  # Déclenche le workflow sur les pushs vers la branche 'main'

jobs:
  connect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval $(ssh-agent -s)
          ssh-add id_ed25519

      - name: Connexion SSH à Alwaysdata
        run: ssh -o StrictHostKeyChecking=no abysse@ssh-abysse.alwaysdata.net
